name: 'Diff line numbers'
description: 'This action outputs the status and the line number of the changed lines of the changed files'
inputs:
  githubToken:  # ${{ secrets.GITHUB_TOKEN }}
    description: 'The GitHub token used by the workflow'
    required: true
outputs:
  files:
    description: "Object with file paths as keys. Each value is { added: number[], removed: number[], status: string }"
runs:
  using: 'node12'
  main: 'dist/index.js'
